const APPEND_MESSAGES = 'APPEND_MESSAGES';
const REQUEST_POSTBOX_ASYNC = 'REQUEST_POSTBOX_ASYNC';
const ADD_LATEST = 'ADD_LATEST';

export {
  APPEND_MESSAGES,
  REQUEST_POSTBOX_ASYNC,
  ADD_LATEST
};
